version: '3.4'

services:
  weather.api:
    image: ${DOCKER_REGISTRY-}weatherapi
    build:
      context: .
      dockerfile: Weather.API/Dockerfile
    depends_on:
      - sql.server

  sql.server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"   